### ISSUE TITLE
cannot follow

### ISSUE THREAD

**Issue by zeromtmu** [ctrueden/cpij-notebook#1]
an error occurred during install 

conda env create -f environment.yml

`# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/zeromtmu/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/Users/zeromtmu/anaconda2/lib/python2.7/site-packages/conda_env/cli/main.py", line 74, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/zeromtmu/anaconda2/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 79, in execute
        directory=os.getcwd())
      File "/Users/zeromtmu/anaconda2/lib/python2.7/site-packages/conda_env/specs/__init__.py", line 20, in detect
        if spec.can_handle():
      File "/Users/zeromtmu/anaconda2/lib/python2.7/site-packages/conda_env/specs/yaml_file.py", line 14, in can_handle
        self._environment = env.from_file(self.filename)
      File "/Users/zeromtmu/anaconda2/lib/python2.7/site-packages/conda_env/env.py", line 84, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/Users/zeromtmu/anaconda2/lib/python2.7/site-packages/conda_env/env.py", line 72, in from_yaml
        data = yaml_load_standard(yamlstr)
      File "/Users/zeromtmu/anaconda2/lib/python2.7/site-packages/conda/common/serialize.py", line 74, in yaml_load_standard
        return yaml.load(string, Loader=yaml.Loader, version="1.2")
      File "/Users/zeromtmu/anaconda2/lib/python2.7/site-packages/ruamel_yaml/main.py", line 75, in load
        return loader.get_single_data()
      File "/Users/zeromtmu/anaconda2/lib/python2.7/site-packages/ruamel_yaml/constructor.py", line 60, in get_single_data
        node = self.get_single_node()
      File "/Users/zeromtmu/anaconda2/lib/python2.7/site-packages/ruamel_yaml/composer.py", line 53, in get_single_node
        document = self.compose_document()
      File "/Users/zeromtmu/anaconda2/lib/python2.7/site-packages/ruamel_yaml/composer.py", line 76, in compose_document
        self.get_event()
      File "/Users/zeromtmu/anaconda2/lib/python2.7/site-packages/ruamel_yaml/parser.py", line 136, in get_event
        self.current_event = self.state()
      File "/Users/zeromtmu/anaconda2/lib/python2.7/site-packages/ruamel_yaml/parser.py", line 215, in parse_document_end
        token = self.peek_token()
      File "/Users/zeromtmu/anaconda2/lib/python2.7/site-packages/ruamel_yaml/scanner.py", line 144, in peek_token
        self.fetch_more_tokens()
      File "/Users/zeromtmu/anaconda2/lib/python2.7/site-packages/ruamel_yaml/scanner.py", line 239, in fetch_more_tokens
        return self.fetch_value()
      File "/Users/zeromtmu/anaconda2/lib/python2.7/site-packages/ruamel_yaml/scanner.py", line 598, in fetch_value
        self.get_mark())
    ScannerError: mapping values are not allowed here
      in "<byte string>", line 578, column 24:
          <!-- blob contrib key: blob_contributors:v21:32926a57 ... 
                               ^

`$ /Users/zeromtmu/anaconda2/bin/conda-env create -f environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
               CONDA_ROOT=/Users/zeromtmu/anaconda2
                     PATH=/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/zeromtmu/
                          anaconda2/bin:/Users/zeromtmu/anaconda2/bin://anaconda/bin:/Library/Fr
                          ameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bi
                          n:/usr/sbin:/sbin:/Users/zeromtmu:/Library/TeX/texbin:/opt/ImageMagick
                          /bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /Users/zeromtmu/.condarc
 populated config files : /Users/zeromtmu/.condarc
          conda version : 4.5.5
    conda-build version : not installed
         python version : 2.7.14.final.0
       base environment : /Users/zeromtmu/anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/zeromtmu/anaconda2/pkgs
                          /Users/zeromtmu/.conda/pkgs
       envs directories : /Users/zeromtmu/anaconda2/envs
                          /Users/zeromtmu/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.5 requests/2.19.1 CPython/2.7.14 Darwin/17.6.0 OSX/10.13.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.`

**Comment by ctrueden** [comment]
Have you tried with conda 3 instead of conda 2?

**Comment by zeromtmu** [comment]
Yes t try to used python3 is it possible?

-- 
Naravut Suvannang

On 10 July BE 2561 at 03:24:33, Curtis Rueden (notifications@github.com)
wrote:

Have you tried with conda 3 instead of conda 2?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/CellProfiler/notebooks/issues/1#issuecomment-403608430>,
or mute the thread
